---
abstract: 'Interface to Paperless Transaction Corporation BackOffice API'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-PaperlessTrans
no_index:
  file:
    - perlcritic.rc
provides:
  Business::OnlinePayment::PaperlessTrans:
    file: lib/Business/OnlinePayment/PaperlessTrans.pm
    version: 0.001004
requires:
  LWP::Protocol::https: 0
resources:
  bugtracker: https://github.com/xenoterracide/business-onlinepayment-paperlesstrans/issues
  homepage: https://metacpan.org/release/Business-OnlinePayment-PaperlessTrans
  repository: git://github.com/xenoterracide/business-onlinepayment-paperlesstrans.git
version: 0.001004
